// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// audio_i2s //
// --------- //

#define audio_i2s_wrap_target 0
#define audio_i2s_wrap 22

#define audio_i2s_offset_entry_point 17u
#define audio_i2s_offset_stereo 19u
#define audio_i2s_offset_single 21u

static const uint16_t audio_i2s_program_instructions[] = {
            //     .wrap_target
    0x1863, //  0: jmp    !y, 3           side 2     
    0x80a0, //  1: pull   block                      
    0x0006, //  2: jmp    6                          
    0xa042, //  3: nop                               
    0x0006, //  4: jmp    6                          
    0xba42, //  5: nop                    side 2 [2] 
    0x6001, //  6: out    pins, 1                    
    0x1f45, //  7: jmp    x--, 5          side 3 [3] 
    0xb042, //  8: nop                    side 0     
    0x6201, //  9: out    pins, 1                [2] 
    0xf63e, // 10: set    x, 30           side 1 [2] 
    0x80a0, // 11: pull   block                      
    0xb242, // 12: nop                    side 0 [2] 
    0x6001, // 13: out    pins, 1                    
    0x174c, // 14: jmp    x--, 12         side 1 [3] 
    0xba42, // 15: nop                    side 2 [2] 
    0x6001, // 16: out    pins, 1                    
    0xfe3e, // 17: set    x, 30           side 3 [2] 
    0x0000, // 18: jmp    0                          
    0xe041, // 19: set    y, 1                       
    0x0000, // 20: jmp    0                          
    0xe040, // 21: set    y, 0                       
    0x0000, // 22: jmp    0                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program audio_i2s_program = {
    .instructions = audio_i2s_program_instructions,
    .length = 23,
    .origin = -1,
};

static inline pio_sm_config audio_i2s_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + audio_i2s_wrap_target, offset + audio_i2s_wrap);
    sm_config_set_sideset(&c, 3, true, false);
    return c;
}
#endif

