// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// audio_i2s //
// --------- //

#define audio_i2s_wrap_target 0
#define audio_i2s_wrap 11

#define audio_i2s_offset_entry_point 11u

static const uint16_t audio_i2s_program_instructions[] = {
            //     .wrap_target
    0xb842, //  0: nop                    side 2     
    0x6201, //  1: out    pins, 1                [2] 
    0x1f40, //  2: jmp    x--, 0          side 3 [3] 
    0xb042, //  3: nop                    side 0     
    0x6201, //  4: out    pins, 1                [2] 
    0xf72e, //  5: set    x, 14           side 1 [3] 
    0xb042, //  6: nop                    side 0     
    0x6201, //  7: out    pins, 1                [2] 
    0x1746, //  8: jmp    x--, 6          side 1 [3] 
    0xb842, //  9: nop                    side 2     
    0x6201, // 10: out    pins, 1                [2] 
    0xff2e, // 11: set    x, 14           side 3 [3] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program audio_i2s_program = {
    .instructions = audio_i2s_program_instructions,
    .length = 12,
    .origin = -1,
};

static inline pio_sm_config audio_i2s_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + audio_i2s_wrap_target, offset + audio_i2s_wrap);
    sm_config_set_sideset(&c, 3, true, false);
    return c;
}

static inline void audio_i2s_program_init(PIO pio, uint sm, uint offset, uint data_pin, uint clock_pin_base) {
    pio_sm_config sm_config = audio_i2s_program_get_default_config(offset);
    sm_config_set_out_pins(&sm_config, data_pin, 1);
    sm_config_set_sideset_pins(&sm_config, clock_pin_base);
    sm_config_set_out_shift(&sm_config, false, true, 32);
    pio_sm_init(pio, sm, offset, &sm_config);
    uint pin_mask = (1u << data_pin) | (3u << clock_pin_base);
    pio_sm_set_pindirs_with_mask(pio, sm, pin_mask, pin_mask);
    pio_sm_set_pins(pio, sm, 0); // clear pins
    pio_sm_exec(pio, sm, pio_encode_jmp(offset + audio_i2s_offset_entry_point));
}

#endif

